name: Leaders Lead
favicon: null
layout_spectrum: 0.038623382803052664
typography_spectrum: 0.7178192692808807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7212582635693252
  lightness: 0.6460104519501328
  saturation: 0.4877207644749433
  rhythmicContrast: 0.22692848928272724
purpose: []
